export default {
  stripe_public_key: 'pk_test_replacethiswithyourtestkey',
  lms_api_url: 'https://dev.harperdbcloudservices.com/',
  google_analytics_code: 'UA-98232508-3',
  youtube_api_key: 'AIzaSyDcAYCF6FFfEvZ45lzyizdQOeb5-daqLWc',
  tc_version: '2020-01-01',
  refresh_api_timeout: 300000,
  instances_refresh_rate: 10000,
  instance_refresh_rate: 5000,
  total_cloud_instance_limit: 10,
  free_cloud_instance_limit: 1,
  total_local_instance_limit: false,
  free_local_instance_limit: false,
  max_file_upload_size: 10380902,
  studio_version: '1.0.1',
  user_guide_id: 16032,
  maintenance: 0,
};
