export default {
  env: 'dev',
  stripe_public_key: 'pk_test_XXXXXXXXXXXXXXXXXXXXXX',
  lms_api_url: 'XXXXXXXXXXXXXXXXXXXXXXXX',
  google_analytics_code: 'UA-XXXXXXXXXXXXX-3',
  youtube_api_key: 'XXXXXXXXXXXXXXXXXXXXXX',
  postman_collection_url: 'https://www.postman.com/collections/ac7c0401b58b3ffde967',
  tc_version: '2020-01-01',
  check_version_interval: 300000,
  refresh_content_interval: 10000,
  total_cloud_instance_limit: 10,
  free_cloud_instance_limit: 1,
  total_local_instance_limit: false,
  free_local_instance_limit: false,
  max_file_upload_size: 10380902,
  studio_version: '1.2.1',
  user_guide_id: 16032,
  maintenance: 0,
  errortest: 0,
};
