name: Playwright Tests
on:
  push:
    branches: [ STUDIO-7 ]
  pull_request:
    branches: [ master, stage ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 14.17.3
    - name: Install local CA for https tests
      run: |
        #!/bin/bash
        
        # install cert-util
        sudo apt install libnss3-tools

        # install mkcert from pre-existing binaries
        curl -JLO "https://dl.filippo.io/mkcert/latest?for=linux/amd64"
        chmod +x mkcert-v*-linux-amd64
        sudo cp mkcert-v*-linux-amd64 /usr/local/bin/mkcert 

        # create a local CA 
        mkcert -install

        # create a local dir for cert and key files
        mkdir -p .cert

        # cert and key files
        mkcert -key-file ./.cert/key.pem -cert-file ./.cert/cert.pem "localhost"
    - name: Install dependencies
      run: yarn
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
